In [2]:
# importing necessary libraries
import pandas as pd
import glob
import numpy as np
import warnings
import os

In [21]:
# Saccade Length Tree General
path_tree_general = os.getcwd() + "/data" + "/Tree General"
filenames_tree_general = glob.glob(path_tree_general + "/*FXD.*")

saccade_averages = []
# Each Users Saccade-Lengths/Average between fixation points
for filename in filenames_tree_general:
    # Initial Data
    tree_general = []
    tree_general.append(pd.read_csv(filename, sep = '\t', header = None, error_bad_lines=False, warn_bad_lines=False))
    tree_general_fxd_df = pd.concat(tree_general, ignore_index=True)
    tree_general_fxd_df.shape
    tree_general_fxd_df.rename(columns = {0:'number', 
                     1: 'time', 
                     2: 'duration', 
                     3: 'screen_x', 
                     4: 'screen_y'}, inplace = True)

    # Saccade Lengths 
    x = (tree_general_fxd_df['screen_x'] - tree_general_fxd_df['screen_x'].shift())
    y = (tree_general_fxd_df['screen_y'] - tree_general_fxd_df['screen_y'].shift())
    tree_general_fxd_df['saccade_length'] = np.sqrt(x**2 + y**2)

    # Find Average for user 
    saccade_averages.append(tree_general_fxd_df['saccade_length'].mean())

In [29]:
tree_general_saccade_df = pd.DataFrame()
tree_general_saccade_df['saccade_averages'] = saccade_averages

In [30]:
tree_general_saccade_df

    saccade_averages
0         107.837066
1         162.398925
2         136.381810
3         126.047521
4         123.172808
5         182.981961
6         129.809541
7         135.016294
8         135.821528
9         160.957808
10        122.355971
11        120.679906
12        170.602905
13        142.944757
14        215.139740
15        121.695985